name: Release Please Workflow

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_ID_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: simple
