name: Test Github Actions Dynamic Matrix 
on:
  workflow_dispatch:
    inputs:
      eniroment:
        description: 'Enviroment to be deployed'
        required: true
        default: 'dev'
        type: choice
        options:
          - int
          - testing
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      enviroments: ${{ steps.enviroments.outputs.value }}
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v3.0.0
      - id: enviroments
        run: |
          env_list='"dev"'
          for e in "int" "testing"
          do
            if [[ "$MESSAGE" == *"/deploy $e"* || "${{ inputs.eniroment }}" == "$e" ]] ; then
              env_list+=",\"$e\""
            fi
          done
          echo "value=[$env_list]" >> $GITHUB_OUTPUT
        env:
          MESSAGE: ${{github.event.head_commit.message}}
      - run: |
          echo "${{ steps.enviroments.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enviroment: ${{fromJSON(needs.setup.outputs.enviroments)}}
    steps:
      - run: |
          echo "${{ matrix.enviroment }}"
