name: Pull Request Tests

on:
  merge_group:
    types: [ checks_requested ]
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - .github/**
      - '!*.md'
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
    paths:
      - '**'
      - '!*.md'

  workflow_dispatch:
    inputs:
      skip-sonar:
        description: 'Skip Sonar check'
        required: true
        type: choice
        options:
          - "true"
          - "false"
        default:
          "false"



concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - uses: actions/checkout@v4
      - name: Run Backend tests
        run: echo "Running Backend tests"

  frontend-unit-tests:
    runs-on: ubuntu-latest
    name: Build Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Frontend tests
        run: echo "Running Frontend tests"